version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: test-password
      POSTGRES_DB: db
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
